import { build } from "esbuild";
import {
  readFileSync,
  writeFileSync,
  mkdirSync,
  mkdtempSync,
  rmSync,
} from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";
import { tmpdir } from "node:os";

const root = dirname(dirname(fileURLToPath(import.meta.url)));
const skill = resolve(root, "plugins/musekit/skills/diagram-design");
const checking = process.argv.includes("--check");
const result = await build({
  entryPoints: [resolve(skill, "src/runtime.js")],
  bundle: true,
  minify: true,
  charset: "utf8",
  format: "iife",
  platform: "browser",
  target: "chrome110",
  write: false,
  legalComments: "none",
});
const license = readFileSync(
  resolve(root, "node_modules/html-to-image/LICENSE"),
  "utf8",
).trim();
const output = `/* Musekit diagram runtime. Generated by npm run build:diagram.\n * Includes html-to-image 1.11.13 (MIT).\n${license}\n*/\n${result.outputFiles[0].text}`;
const target = resolve(skill, "assets/diagram-runtime.js");
mkdirSync(dirname(target), { recursive: true });
if (checking) {
  if (readFileSync(target, "utf8") !== output)
    throw Error("Diagram runtime is stale; run npm run build:diagram");
} else writeFileSync(target, output);
const work = mkdtempSync(resolve(tmpdir(), "musekit-build-"));
try {
  for (const name of ["architecture", "decision", "sequence", "state"]) {
    const source = resolve(skill, "references/examples/source", `${name}.html`),
      file = resolve(skill, "references/examples", `${name}.html`);
    const output = checking ? resolve(work, `${name}.html`) : file;
    execFileSync(
      "python3",
      [
        resolve(skill, "scripts/prepare_diagram.py"),
        source,
        "--output",
        output,
      ],
      { stdio: checking ? "pipe" : "inherit" },
    );
    if (checking && readFileSync(output, "utf8") !== readFileSync(file, "utf8"))
      throw Error(`${name} example is stale; run npm run build:diagram`);
  }
} finally {
  rmSync(work, { recursive: true, force: true });
}
